// Typelizer digest c073638594193ae198001049b38fb396
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Game} from '@/types'

type GamesIndex = {
  games: Array<Game>;
}

export default GamesIndex;
