// Typelizer digest 43cb5b46e1b53cdbbf496c1ef6e6833c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Game} from '@/types'

type GamesEdit = {
  game: Game;
}

export default GamesEdit;
