// Typelizer digest 6c5e332a047566142fd047619a706c99
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Game = {
  id: number;
  title: string | null;
  coverImageUrl: string | null;
  releaseYear: number | null;
}

export default Game;
