// Typelizer digest bd6956912b067075467673ffe13d94a8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Game} from '@/types'

type GamesShow = {
  game: Game;
}

export default GamesShow;
