// Typelizer digest 8f577d5d43f37767ad414838833a4620
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Game} from '@/types'

type GamesNew = {
  game: Game;
}

export default GamesNew;
