// Typelizer digest 064d017928b34ec2fabfba14a051560c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type { default as Game } from './Game'
export type { default as GamesEdit } from './GamesEdit'
export type { default as GamesIndex } from './GamesIndex'
export type { default as GamesNew } from './GamesNew'
export type { default as GamesShow } from './GamesShow'
