// Typelizer digest 17e9f89caf5973b45d6a6883d41cf418
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /games */
  games: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/games', {}, options),
    method: 'get',
  }),

  /** POST /games */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/games', {}, options),
    method: 'post',
  }),

  /** GET /games/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/games/new', {}, options),
    method: 'get',
  }),

  /** GET /games/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/games/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /games/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/games/:id', params, options),
    method: 'get',
  }),

  /** PATCH /games/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/games/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /games/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/games/:id', params, options),
    method: 'delete',
  }),

  /** GET / */
  root: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/', {}, options),
    method: 'get',
  }),
}
